// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

export const environment = {
  myUrl: 'http://localhost:4200',
  adminUrl: 'http//localhost:4200/admin/login',
  // adminUrl: 'http://ec2-18-218-133-217.us-east-2.compute.amazonaws.com:91/admin/login',
  // myUrl: 'http://ec2-18-218-133-217.us-east-2.compute.amazonaws.com:91',
  production: false,
  SERVER_URL: 'http://localhost:8000',
  // SERVER_URL: 'http://ec2-18-218-133-217.us-east-2.compute.amazonaws.com:8000',
  appStatus: 'Please check your internet connection.',
  wrongPassword: 'You entered wrong password.',
  emailNotExist: 'This email is not registered.',
  serverError: 'Server not responding',
  loggedIn: 'You have successfully loggedin',
  registered: 'You have successfully created your account',
  emptySearch: 'Please type first, before searching',
  fileUpload: 'Be sure that you have uploaded your file.',
  fileType: 'Please select valid file type',
  thumbnail: 'Please upload Main Cover and Thumbnail',
  video: 'Please select only video for Preview video',
  price: 'Please add some price for your product',
  multipleLicensePrice: 'Please add some Multiple License Price',
  fitnessTest: 'Please select related fitness',
  fitnessLength: 'You can only select upto three related fitness items',
  nullEmail: 'Your email field is empty',
  nullConfirmEmail: 'Your confirm email is empty',
  confirmEmail: 'Your emails does not match',
  validEmail: 'Your email is not valid',
  nullUserName: 'Your name field is empty',
  nullLocation: 'Your location field is empty',
  nullPassword: 'Your password field is empty',
  nullConfirmPassword: 'Your location field is empty',
  confirmPassword: 'Your password does not match',
  nullIam: 'Your i am a field is empty',
  nullMainInterestOfFitness: 'Your main interest field is empty',
  productSeller: 'Please regiter first as seller',
  clarityRating: 'Please rate clarity',
  creativityRating: 'Please rate creativity',
  thoroughnessRating: 'Please rate thoroughness',
  practicalityRating: 'Please rate practicality',
  accuracyRating: 'Please rate accuracy',
  overallQualityRating: 'Please rate overallQuality',
  commentRating: 'Please add comment',
};

